site_name: Fucking Chen's Blog
theme: material
nav:
  - Home: index.md
  - zookeeper学习: 
    - zookeeper常用命令: zookeeper/command.md
  # - dubbo学习:
    # - draft: dubbo/draft.md
  - docker 学习笔记: 
    - getStarted: docker/getStarted.md